const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const typeRouter = require('./typeRouter')
const productRouter = require('./productRouter')
const basketRouter = require('./basketRouter')
const orderRouter = require('./orderRouter')
const notificationRouter = require('./notificationRouter')
const historyRouter = require('./historyRouter')
const sewingRouter = require('./sewingRouter')
const fittingRouter = require('./fittingRouter')
const bookingRouter = require('./bookingRouter')
const feedbackRouter = require('./feedbackRouter')
const messageRouter = require('./messageRouter')
const staffRouter = require('./staffRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/product', productRouter)
router.use('/basket', basketRouter)
router.use('/order', orderRouter)
router.use('/notification', notificationRouter)
router.use('/history', historyRouter)
router.use('/sewing', sewingRouter)
router.use('/fitting', fittingRouter)
router.use('/booking', bookingRouter)
router.use('/feedback', feedbackRouter)
router.use('/message', messageRouter)
router.use('/staff', staffRouter)

module.exports = router